### ISSUE TITLE
FATAL: Error, the fuse library (libfuse.so.x from fuse2, *not* fuse3) must be installed

### ISSUE THREAD

**Issue by WhosMyName** [Nuitka/Nuitka-Action#10]
Based on my run using the linux runner there is an mismatch in the provided libs.
See this [run](https://github.com/WhosMyName/RealBandcampMusicDiscovery/actions/runs/3847385762/jobs/6555464711#step:5:137).

**Comment by kayhayen** [comment]
@jimkring the needs for libfuse was a thing when Nuitka was still using a special package on Linux, but this is no longer true, so there is no need to check this. I will create a PR if I figure out how to do it. :)

**Comment by kayhayen** [comment]
Ah wait, this is using ancient Nuitka 0.9 and Nuitka is the one asking for it. That is of couse unsupported.
