### ISSUE TITLE
Error building for PySide6/WebEngine on Mac

### ISSUE THREAD

**Issue by scottrules44** [Nuitka/Nuitka-Action#13]
I am trying to build for Mac via this action. 
And I keep getting 
"FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PySide6/Qt/resources'"

https://github.com/scottrules44/SBrowser/actions/runs/4391129829/jobs/7690071279

This error seems to go away if I remove "PyQt6-WebEngine" from my install and "QtWebEngineWidgets" from my code, but I don't want to do that.

Repo:
https://github.com/scottrules44/SBrowser

**Comment by kayhayen** [comment]
You are using old Nuitka, try 1.4.8 or 1.5 instead. The action release still defaults to the old release. We have not found the time to update it yet, it's also not fully announced yet.

@jimkring how to make a new release?

**Comment by kayhayen** [comment]
Please checkout the docs. I also releases v0.5 of the action, but you should switch from using `@0.4` to `@main` to avoid this issue in the future. By default Nuitka follows now the stable releases. You can specify your own version now of coruse too, and even branch names. I recommand using the default "main" as that makes you follow Nuitka releases automatically.
