### ISSUE TITLE
Add --low-memory

### ISSUE THREAD

**Issue by Xpl0itU** [Nuitka/Nuitka-Action#18]
I often run out of heap memory while building on CI due to yt-dlp, hopefully with this function it can be fixed

**Comment by kayhayen** [comment]
Not sure if this makes that much sense, maybe you want to report the trouble make to the main Nuitka repo. Otherwise, a PR that adds the option will be accepted of course.

**Comment by kayhayen** [comment]
Closing for lack of feedback.
