### ISSUE TITLE
Add --include-module option

### ISSUE THREAD

**Issue by GOOD-AN** [Nuitka/Nuitka-Action#23]
I'm creating an application with the apscheduler library, but since the package cannot include apscheduler.triggers.date, I need the following command:
```
$ python -m nuitka --standalone --include-module=apscheduler.triggers.date main.py
```
However, when it is actually used, the command is missing.

**Comment by kayhayen** [comment]
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by kayhayen** [comment]
It's not at all clear, what you are trying to say. This might be a misguided report. I do not know if this is for Nuitka Actions or Nuitka.

**Comment by GOOD-AN** [comment]
I apologize for not being clear, I added the include-module parameter when using Nuitka Actions, but when I actually ran it, the output instructions did not have this parameter, the screenshot is as follows:

**Configuration file:**
![image](https://github.com/Nuitka/Nuitka-Action/assets/53306377/15998ab7-2870-4888-896b-87510d45a9d7)

**Output:**
![image](https://github.com/Nuitka/Nuitka-Action/assets/53306377/e0626374-e4d2-4e87-9e2d-de7ddee0ac83)
