### ISSUE TITLE
Add --include-module option

### ISSUE THREAD

**Issue by GOOD-AN** [Nuitka/Nuitka-Action#25]
I apologize for not being clear in my last issue, but since that issue was closed and replies were not responded to, I had to reopen an issue to explain the problem I was having.

I added the include-module parameter when using Nuitka Actions, but when I actually ran it, the output instructions did not have this parameter, the screenshot is as follows:

**Configuration file:**
![image](https://github.com/Nuitka/Nuitka-Action/assets/53306377/15998ab7-2870-4888-896b-87510d45a9d7)

**Output:**
![image](https://github.com/Nuitka/Nuitka-Action/assets/53306377/e0626374-e4d2-4e87-9e2d-de7ddee0ac83)

**Comment by kayhayen** [comment]
Ah, so what you are saying is that it has not had the intended effect. btw: please avoid screenshots for textual information.

I can see that. The `apscheduler` will get beyond 1.6 support for doing it automatically maybe., but that's not there, and not what this is about now.

I have added the option on `main` right now, try again and let me know if it works now, it should.

**Comment by GOOD-AN** [comment]
I'm very sorry, I'll avoid using screenshots for textual information later.

Thank you very much for the fix, it works perfectly now!
