### ISSUE TITLE
Option onefile-tempdir-spec bypassed

### ISSUE THREAD

**Issue by zak-45** [Nuitka/Nuitka-Action#36]
Hi, 
looks like the onefile-tempdir-spec is not taken in consideration.
when I run the exe file, this still continue to extract it on %TMP% folder.

Step on my action:

       -name: Build Executable for ${{runner.os}}
        uses: Nuitka/Nuitka-Action@v0.6
        with:
          nuitka-version: main
          script-name: main.py          
          onefile: true
          onefile-tempdir-spec: ./WLEDAudioSyncRTMood
          include-data-dir: assets=assets
          output-file: WLEDAudioSyncRTMood-${{runner.os}}

Log file from my runned action:

`
Run Nuitka/Nuitka-Action@v0.6
  with:
    nuitka-version: main
    script-name: main.py
    onefile: true
    **onefile-tempdir-spec: ./WLEDAudioSyncRTMood**
    include-data-dir: assets=assets
    output-file: WLEDAudioSyncRTMood-Windows
    working-directory: .
    module: false
    standalone: true
    assume-yes-for-downloads: true
    show-scons: true
    onefile-no-compression: false
    deployment: false
    output-dir: build
    enable-console: true
    disable-console: false
    windows-uac-admin: false
    windows-uac-uiaccess: false
    mingw64: false
    macos-create-app-bundle: false
    encrypt-stdout: false
    encrypt-stderr: false
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.8.10\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.8.10\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
Run echo "NUITKA_CACHE_DIR=D:\a\_actions\Nuitka\Nuitka-Action\v0.6/nuitka/cache" >> $GITHUB_ENV
Run pip install -r "D:\a\_actions\Nuitka\Nuitka-Action\v0.6/requirements.txt"
Collecting ordered-set==4.1.0 (from -r D:\a\_actions\Nuitka\Nuitka-Action\v0.6/requirements.txt (line 7))
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting wheel==0.38.4 (from -r D:\a\_actions\Nuitka\Nuitka-Action\v0.6/requirements.txt (line 9))
  Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting zstandard==0.20.0 (from -r D:\a\_actions\Nuitka\Nuitka-Action\v0.6/requirements.txt (line 11))
  Using cached zstandard-0.20.0-cp38-cp38-win_amd64.whl (644 kB)
Installing collected packages: zstandard, wheel, ordered-set
Successfully installed ordered-set-4.1.0 wheel-0.38.4 zstandard-0.20.0

Notice:  A new release of pip is available: 23.3 -> 23.3.1
Notice:  To update, run: python.exe -m pip install --upgrade pip
Collecting nuitka
  Cloning https://github.com/Nuitka/Nuitka.git/ (to revision main) to c:\users\runneradmin\appdata\local\temp\pip-install-4ff3m1ab\nuitka_b3f6ccbcf33c469fae2199fac95619e8
  Running command git clone --filter=blob:none --quiet https://github.com/Nuitka/Nuitka.git/ 'C:\Users\runneradmin\AppData\Local\Temp\pip-install-4ff3m1ab\nuitka_b3f6ccbcf33c469fae2199fac95619e8'
  Running command git checkout -b main --track origin/main
  branch 'main' set up to track 'origin/main'.
  Switched to a new branch 'main'
  Resolved https://github.com/Nuitka/Nuitka.git/ to commit 5a2d18f027031a9b1b39e81ff3c03e08f0ca172b
  Running command git submodule update --init --recursive -q
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: ordered-set>=4.1.0 in c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages (from nuitka) (4.1.0)
Requirement already satisfied: zstandard>=0.15 in c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages (from nuitka) (0.20.0)
Building wheels for collected packages: nuitka
  Building wheel for nuitka (pyproject.toml): started
  Building wheel for nuitka (pyproject.toml): finished with status 'done'
  Created wheel for nuitka: filename=Nuitka-1.8.4-cp38-cp38-win_amd64.whl size=2942697 sha256=c3bf35912c831cf61192d87f9b4176e170fd2ba5aad0d9027c3ef91072580ff7
  Stored in directory: C:\Users\runneradmin\AppData\Local\Temp\pip-ephem-wheel-cache-760rsmaz\wheels\71\9e\d0\f505e86d3117e0b9bf4d57c59df42f91ea732fb3980b600661
Successfully built nuitka
Installing collected packages: nuitka
Successfully installed nuitka-1.8.4

Notice:  A new release of pip is available: 23.3 -> 23.3.1
Notice:  To update, run: python.exe -m pip install --upgrade pip
Run actions/cache@v3
Received 0 of 101936585 (0.0%), 0.0 MBs/sec
Received 83886080 of 101936585 (82.3%), 39.9 MBs/sec
Cache Size: ~97 MB (101936585 B)
"C:\Program Files\Git\usr\bin\tar.exe" -xf D:/a/_temp/29bc150f-08d5-4cde-8dea-98837d5351b2/cache.tzst -P -C D:/a/WLEDAudioSyncRTMood/WLEDAudioSyncRTMood --force-local --use-compress-program "zstd -d"
Received 101936585 of 101936585 (100.0%), 32.3 MBs/sec
Cache restored successfully
Cache restored from key: Windows-python-3.8-nuitka-b0ad8cdebfb0253fb21cec543c1e433238da202f
Run set -e
**Nuitka-Options:INFO: Used command line options: --standalone --onefile --show-scons --assume-yes-for-downloads --output-dir=build --output-filename=WLEDAudioSyncRTMood-Windows --enable-console --include-data-dir=assets=assets main.py**
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.4' on Python '3.8' commercial grade 'not installed'.`

Thanks

**Comment by kayhayen** [comment]
Yes, that's very strange, probably not defined in the action.yml and GitHub just ignores and does not expose content not matching it.

**Comment by zak-45** [comment]
just to share more log with you. this is what I have been able to see also :

Received 163193675 of 163193675 (100.0%), 77.4 MBs/sec
Cache restored successfully
Cache restored from key: Linux-python-3.8-nuitka-af2948d0889c21e43d8da8643fb8385f339df165
Run set -e
  set -e
  ARGS=""
  if [ "false" == "true" ]; then
    ARGS+=" --module"
  fi
  if [ "true" == "true" ]; then
    ARGS+=" --standalone"
  fi
  if [ "true" == "true" ]; then
    ARGS+=" --onefile"
  fi
  **if [ "./WLEDAudioSyncRTMood" == "true" ]; then
    ARGS+=" --onefile-tempdir-spec=./WLEDAudioSyncRTMood"
  fi**
  if [ "" != "" ]; then
    ARGS+=" --onefile-child-grace-time="
  fi

**Comment by kayhayen** [comment]
Ah, `main` should not have it. With the last release we changed how Nuitka is invoked entirely.

**Comment by kayhayen** [comment]
I just made a 1.0 release, and I would assume it improves that.
