### ISSUE TITLE
FATAL: tk-inter: Could not find Tcl, you might need to use '--tcl-library-dir' and if that works, report a bug so it can be added to Nuitka.

### ISSUE THREAD

**Issue by sachinsenal0x64** [Nuitka/Nuitka-Action#37]
OSX build was failed, any solution ?

![image](https://github.com/Nuitka/Nuitka-Action/assets/127573781/f253ec6d-aa08-4fd6-80d9-b5eeda408bb5)

**Comment by kayhayen** [comment]
That's is not an issue of Nuitka-Action, make a proper report to Nuitka repository instead.
