### ISSUE TITLE
FATAL Error: "Nuitka does not work in --standalone or --onefile on Windows without."

### ISSUE THREAD

**Issue by WonSNoJ** [Nuitka/Nuitka-Action#39]
I'm getting the following line when trying to compile using GitHub Actions:
`FATAL: Nuitka does not work in --standalone or --onefile on Windows without.`

I'm basing my actions workflow around several examples posted here, and I wasn't able to get anywhere. Here's part of the log:
```
Nuitka-Options:INFO: Used command line options: --onefile --output-dir=build --script-name=main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.7' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 17 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 17 C files using clcache with 0 cache hits and 17 cache misses.
Nuitka will make use of Dependency Walker (https://dependencywalker.com/) tool
FATAL: Nuitka does not work in --standalone or --onefile on Windows without.
to analyze the dependencies of Python extension modules.

Is it OK to download and put it in 'D:\a\_actions\Nuitka\Nuitka-Action\main/nuitka/cache\downloads\depends\x86_64'.

Fully automatic, cached. Proceed and download? [Yes]/No : 
Error: Process completed with exit code 1.
```

My assumption is that it isn't downloading Dependency Walker, due to a prompt for some reason. Here's my GitHub Action in its current state (I've tried a number of revisions):

https://gist.github.com/WonSNoJ/ad1d410668863c1aafe3455a17aaee25

**Comment by WonSNoJ** [comment]
I managed to work around this for now by manually downloading and extracting Depency Walker to `D:\a\_actions\Nuitka\Nuitka-Action\main\nuitka\cache\downloads\depends\x86_64`.

This works for now, but is obviously not ideal. I am sure I did something wrong or am missing something somewhere. I would appreciate any insight you may have to offer.

Thank you!

**Comment by kayhayen** [comment]
The value of `assume-yes-for-downloads` must be yes. Recent changes of mine dropped that, I am going to fix it now.

**Comment by kayhayen** [comment]
Should be good again, the options got their defaults back, and as a bonus, missing "warning control" options were added. The assume downloads is not really that much about warnings, but this was supposed to be a quick fix, not moving it around for now in Nuitka.
