### ISSUE TITLE
Can't Publish Releases on GitHub Marketplace (Nuitka needs to accept Developer Agreement)

### ISSUE THREAD

**Issue by jimkring** [Nuitka/Nuitka-Action#4]
@kayhayen in order to publish releases to the GitHub Marketplace, Nuitka must accept the GitHub Marketplace Developer Agreement.

Can you do that?

Edit a release and you'll see the note:
https://github.com/Nuitka/Nuitka-Action/releases/edit/v0.3.3

<img width="601" alt="image" src="https://user-images.githubusercontent.com/381432/181632246-7691cb75-8dc4-404f-86b5-0461405dbb34.png">

**Comment by kayhayen** [comment]
Do we have to repeat this each time we make a Nuitka-Actions release?

**Comment by kayhayen** [comment]
Of course I did it.

**Comment by jimkring** [comment]
@kayhayen it’s just something the organization has to do once. Thanks for taking care of that.
