### ISSUE TITLE
Could you pls help update the actions/cache to newer version to avoid warning?

### ISSUE THREAD

**Issue by IcyTide** [Nuitka/Nuitka-Action#42]
While using action from this repo, it will show warning as below:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

using actions/cache@v4 will work well

**Comment by kayhayen** [comment]
So, I did a 1.1 release which I intended to do anyway, before that, and for main I bumped the cache action. Let me know if that works, I didn't find any differences really.

**Comment by IcyTide** [comment]
work well now, no warning anymore.
