### ISSUE TITLE
Nuitka cache support custom fields or add arch info

### ISSUE THREAD

**Issue by renyijiu** [Nuitka/Nuitka-Action#57]
https://github.com/Nuitka/Nuitka-Action/blob/e4a28989f103e54c93e8a7ccc715751d5dbb5c98/action.yml#L491

According to the settings here, the current system and Python version determine the cache information. However, when compiling on x86_64 and arm64 with the same code on x86_64 and arm runner, the cache names will be the same. I don’t know if this will cause compilation problems? If so, it is recommended to add arch information

**Comment by kayhayen** [comment]
Do you happen know what environment would be good to use there, I assume GitHub has something for that.

**Comment by renyijiu** [comment]
> Do you happen know what environment would be good to use there, I assume GitHub has something for that.

https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context

there is a `runner.arch` context variable defined, could use it.

**Comment by kayhayen** [comment]
Thanks for the pointer; I pushed it to `main.` Let me know if it works; it should be only better. I would assume that the `ccache` cannot collide because pre-processor differences are essentially a given, but sharing them also makes absolutely no sense.

**Comment by renyijiu** [comment]
It seems that forgot to update the `action.yml` file and only updated the template file.

**Comment by kayhayen** [comment]
Ah, yes, you are correct, let me merge your PR then, it should have the same effect as re-creating it.
