### ISSUE TITLE
nuitka FATAL: Error, unknown plug-in '' referenced.

### ISSUE THREAD

**Issue by hoijui** [Nuitka/Nuitka-Action#7]
I am using the GitHub action, and I have no plugins defined, so I do not know where this comes from.

Failed CI Run: https://github.com/hoijui/BundleBuilder/actions/runs/3255646292/jobs/5345181798
GH Action definition: https://github.com/hoijui/BundleBuilder/commit/3a1e21c

Nuitka/Nuitka-Action@v0.4
Python 3.10

**Comment by hoijui** [comment]
makes sense, yeah!
I did not see that in the [action.yml](https://github.com/Nuitka/Nuitka-Action/blob/main/action.yml), though, but maybe there is something going on there that makes the bash-code generate that empty option, hm!

**Comment by kayhayen** [comment]
@jimkring did you see this, I transferred it from Nuitka. I will still not get the generic argument parsing from Yaml done for a while, but I think this is a very valid beginner trap

**Comment by BlackCatDevel0per** [comment]
Hello, how can I resolve this problem?

**Comment by BlackCatDevel0per** [comment]
I used action from main branch (Nuitka/Nuitka-Action@main), and it solved the problem 😁
Will the next release be ok?

**Comment by jimkring** [comment]
@BlackCatDevel0per yes :)

**Comment by AntoineKM** [comment]
hey guys this issue still persist, can you release it if it has been solved, please ?

**Comment by kayhayen** [comment]
It seems that the release process is stuck. I want to make the action more ship shape, but I am personally overloaded, and it seems that @jimkring doesn't have the time right now. Not sure if I can make it in 1.6 time frame, with full 3.11 compatibility and performance improvements on the table. Right now I don't even see a release script. If somebody were to fork it, and provide that kind of tool, it would be great. I do not really want to manually tar up something myself right now.

**Comment by kayhayen** [comment]
I have updated the docs. use @main in your Nuitka action reference instead. That is going to keep you on the latest version of the action. I am currently adapting it for 1.4.8 to be used, during that time it will be a bit unstable as I debug it and the ability to provide tags and branch names to the action.

**Comment by kayhayen** [comment]
Ok, this works now. I might be deleting the @0.4 release, which I thought I saw, those seem unnecessary at all.
