### ISSUE TITLE
Used nuitka Version is old

### ISSUE THREAD

**Issue by WhosMyName** [Nuitka/Nuitka-Action#9]
The provided Nuitka Version is 1.2.7, but the current version is 1.3.8.
Best of all the current release still uses Nuitka 0.9.4.
The action should reflect this change and use the current version of nuitka.

(PR ready when needed) #11

**Comment by kayhayen** [comment]
Ah, I get it, we have failed to make releases of the action for a while, that is of course not good. I think we should do that soon.
